import { renderMarkdown } from './markdown.mjs';
import { createTranslator, languageName, localizePath } from './i18n.mjs';
import { escapeAttr, escapeHtml, formatDate, formatMonth, formatYear, safePathSegment, uniqueSorted } from './utils.mjs';
import { ICONS } from './template-core.mjs';
import { renderLayout } from './template-layout.mjs';
import { renderArchiveExplorer } from './template-components.mjs';

export function renderArchivePage(context){const{config,locale,packs,records}=context;const t=createTranslator(locale,packs,config.defaultLocale);const body=`<section class="page-hero section-shell"><p class="eyebrow">${escapeHtml(t('archive.eyebrow'))}</p><h1>${escapeHtml(t('archive.title'))}</h1><p>${escapeHtml(t('archive.description'))}</p></section>${renderArchiveExplorer({records,locale,t,config,syncUrl:true})}`;return renderLayout({...context,pathname:'/archive/',pageTitle:t('archive.title'),description:t('archive.description'),body,bodyClass:'page-archive'});}

export function renderBrowsePage(context){const{config,locale,packs,records}=context;const t=createTranslator(locale,packs,config.defaultLocale);const sections=[
[t('browse.years'),uniqueSorted(records.map(r=>r.year),locale).reverse().map(value=>({label:formatYear(value,locale),count:records.filter(r=>r.year===value).length,href:`/years/${safePathSegment(value)}/`}))],
[t('browse.months'),uniqueSorted(records.map(r=>r.monthKey),locale).reverse().map(value=>({label:formatMonth(value,locale),count:records.filter(r=>r.monthKey===value).length,href:`/months/${safePathSegment(value)}/`}))],
[t('browse.tags'),uniqueSorted(records.flatMap(r=>r.tags),locale).map(value=>({label:`#${value}`,count:records.filter(r=>r.tags.includes(value)).length,href:`/tags/${safePathSegment(value)}/`}))],
[t('browse.projects'),uniqueSorted(records.map(r=>r.project),locale).map(value=>({label:value,count:records.filter(r=>r.project===value).length,href:`/projects/${safePathSegment(value)}/`}))],
[t('browse.types'),uniqueSorted(records.map(r=>r.type),locale).map(value=>({label:t(`types.${value}`),count:records.filter(r=>r.type===value).length,href:`/types/${safePathSegment(value)}/`}))],
[t('browse.languages'),uniqueSorted(records.map(r=>r.lang),locale).map(value=>({label:languageName(value,locale),count:records.filter(r=>r.lang===value).length,href:`/languages/${safePathSegment(value)}/`}))]
];const body=`<section class="page-hero section-shell"><p class="eyebrow">${escapeHtml(t('browse.eyebrow'))}</p><h1>${escapeHtml(t('browse.title'))}</h1><p>${escapeHtml(t('browse.description'))}</p></section><section class="browse-sections section-shell">${sections.map(([title,items],index)=>`<article class="browse-panel"><div class="browse-panel-heading"><span>${String(index+1).padStart(2,'0')}</span><h2>${escapeHtml(title)}</h2></div><div class="browse-links">${items.length?items.map(item=>`<a href="${escapeAttr(localizePath(item.href,locale,config.defaultLocale))}"><strong>${escapeHtml(item.label)}</strong><span>${escapeHtml(t('browse.items',{count:item.count}))}</span>${ICONS.chevron}</a>`).join(''):`<p>${escapeHtml(t('browse.noValues'))}</p>`}</div></article>`).join('')}</section>`;return renderLayout({...context,pathname:'/browse/',pageTitle:t('browse.title'),description:t('browse.description'),body,bodyClass:'page-browse'});}

export function renderAboutPage(context){const{config,locale,packs}=context;const t=createTranslator(locale,packs,config.defaultLocale);const cards=[['01',t('about.ownershipTitle'),t('about.ownershipBody')],['02',t('about.languageTitle'),t('about.languageBody')],['03',t('about.agentTitle'),t('about.agentBody')],['04',t('about.deployTitle'),t('about.deployBody')],['05',t('about.addTitle'),t('about.addBody')],['06',t('about.customizeTitle'),t('about.customizeBody')]];const body=`<section class="about-hero section-shell"><p class="eyebrow">${escapeHtml(t('about.eyebrow'))}</p><h1>${escapeHtml(t('about.title'))}</h1><p>${escapeHtml(t('about.lead'))}</p></section><section class="about-grid section-shell">${cards.map(([n,title,text])=>`<article><span>${n}</span><h2>${escapeHtml(title)}</h2><p>${escapeHtml(text)}</p></article>`).join('')}</section><section class="about-code section-shell"><div><p class="eyebrow">PLAIN FILES, OPEN FORMAT</p><h2>Markdown in. A complete archive out.</h2></div><pre><code>content/records/2026/07/2026-07-10-a-day-worth-keeping.md</code></pre><a href="${escapeAttr(config.repository)}" rel="noreferrer">${escapeHtml(t('common.repository'))}${ICONS.arrow}</a></section>`;return renderLayout({...context,pathname:'/about/',pageTitle:t('about.title'),description:t('about.lead'),body,bodyClass:'page-about'});}

export function renderCollectionPage(context){const{config,locale,packs,records,pathname,pageTitle,eyebrow,description}=context;const t=createTranslator(locale,packs,config.defaultLocale);const body=`<section class="page-hero section-shell"><p class="eyebrow">${escapeHtml(eyebrow)}</p><h1>${escapeHtml(pageTitle)}</h1><p>${escapeHtml(description)}</p></section>${records.length?renderArchiveExplorer({records,locale,t,config}):`<section class="first-record section-shell"><h2>${escapeHtml(t('archive.emptyTitle'))}</h2><p>${escapeHtml(t('archive.emptyBody'))}</p></section>`}`;return renderLayout({...context,pathname,pageTitle,description,body,bodyClass:'page-collection'});}

export function renderRecordPage(context){const{config,locale,packs,records,record,translations=[]}=context;const t=createTranslator(locale,packs,config.defaultLocale);const rendered=renderMarkdown(record.body,{anchorLabel:t('record.anchorLabel'),tableLabel:t('record.tableLabel'),taskComplete:t('record.taskComplete'),taskIncomplete:t('record.taskIncomplete')});const index=records.findIndex(r=>r.url===record.url),newer=index>0?records[index-1]:null,older=index>=0&&index<records.length-1?records[index+1]:null;const toc=rendered.headings.filter(h=>h.level<=3).map(h=>`<li class="toc-level-${h.level}"><a href="#${escapeAttr(h.id)}">${escapeHtml(h.text)}</a></li>`).join('');const translationLinks=translations.filter(item=>item.url!==record.url).map(item=>`<a href="${escapeAttr(localizePath(item.url,locale,config.defaultLocale))}" lang="${escapeAttr(item.lang)}">${escapeHtml(languageName(item.lang,locale))}</a>`).join('');const body=`<article class="record-page" data-record-page>
<header class="record-masthead section-shell"><a class="record-back" href="${escapeAttr(localizePath('/archive/',locale,config.defaultLocale))}">${ICONS.arrow}<span>${escapeHtml(t('record.backArchive'))}</span></a><div class="record-kicker"><span class="type-chip type-${escapeAttr(record.type)}">${escapeHtml(t(`types.${record.type}`))}</span><span>${escapeHtml(t('record.sourceLanguage',{language:languageName(record.lang,locale)}))}</span>${record.sample?`<span>${escapeHtml(t('common.sample'))}</span>`:''}</div><h1 lang="${escapeAttr(record.lang)}" dir="${escapeAttr(record.dir)}">${escapeHtml(record.title)}</h1><p class="record-summary" lang="${escapeAttr(record.lang)}" dir="${escapeAttr(record.dir)}">${escapeHtml(record.summary)}</p><div class="record-meta"><time datetime="${escapeAttr(record.date)}">${escapeHtml(formatDate(record.date,locale))}</time><span>${record.readingMinutes} ${escapeHtml(t('common.minutes'))}</span>${record.project?`<a href="${escapeAttr(localizePath(`/projects/${safePathSegment(record.project)}/`,locale,config.defaultLocale))}">${escapeHtml(record.project)}</a>`:''}</div>${record.cover?`<figure class="record-cover"><img src="${escapeAttr(record.cover)}" alt="${escapeAttr(record.coverAlt)}" fetchpriority="high"></figure>`:''}</header>
<div class="record-layout section-shell"><aside class="record-sidebar"><div class="record-sidebar-card"><h2>${escapeHtml(t('common.contents'))}</h2>${toc?`<ol>${toc}</ol>`:`<p>${escapeHtml(t('common.noContents'))}</p>`}</div>${translationLinks?`<div class="translation-card"><h2>${escapeHtml(t('common.translations'))}</h2><p>${escapeHtml(t('record.translationOf'))}</p><div>${translationLinks}</div></div>`:''}</aside><div class="record-main"><div class="prose" lang="${escapeAttr(record.lang)}" dir="${escapeAttr(record.dir)}">${rendered.html}</div>${record.totalTasks?`<p class="task-summary">${escapeHtml(t('record.tasksProgress',{done:record.completedTasks,total:record.totalTasks}))}</p>`:''}<ul class="record-tags" aria-label="${escapeAttr(t('record.tagsLabel'))}">${record.tags.map(tag=>`<li><a href="${escapeAttr(localizePath(`/tags/${safePathSegment(tag)}/`,locale,config.defaultLocale))}">#${escapeHtml(tag)}</a></li>`).join('')}</ul></div></div>
<nav class="record-pagination section-shell" aria-label="${escapeAttr(t('common.contents'))}">${newer?`<a href="${escapeAttr(localizePath(newer.url,locale,config.defaultLocale))}"><small>${escapeHtml(t('common.previous'))}</small><strong lang="${escapeAttr(newer.lang)}">${escapeHtml(newer.title)}</strong></a>`:'<span></span>'}${older?`<a href="${escapeAttr(localizePath(older.url,locale,config.defaultLocale))}"><small>${escapeHtml(t('common.next'))}</small><strong lang="${escapeAttr(older.lang)}">${escapeHtml(older.title)}</strong></a>`:'<span></span>'}</nav></article>`;return renderLayout({...context,pathname:record.url,pageTitle:record.title,description:record.summary,body,bodyClass:'page-record',type:'article',image:record.cover,publishedDate:`${record.date}T00:00:00Z`,modifiedDate:`${record.updated||record.date}T00:00:00Z`});}

export function render404Page(context){const{config,locale,packs}=context;const t=createTranslator(locale,packs,config.defaultLocale);const body=`<section class="not-found section-shell"><p class="eyebrow">${escapeHtml(t('notFound.eyebrow'))}</p><h1>${escapeHtml(t('notFound.title'))}</h1><p>${escapeHtml(t('notFound.body'))}</p><a class="button-primary" href="${escapeAttr(localizePath('/',locale,config.defaultLocale))}">${escapeHtml(t('notFound.action'))}${ICONS.arrow}</a></section>`;return renderLayout({...context,pathname:'/404/',pageTitle:'404',body,noindex:true,bodyClass:'page-404'});}
