import { createTranslator, localizePath } from './i18n.mjs';
import { escapeAttr, escapeHtml, formatDate, groupBy } from './utils.mjs';
import { ICONS } from './template-core.mjs';
import { renderLayout } from './template-layout.mjs';
import { renderArchiveExplorer, renderFirstRecord, renderSectionLabel, renderSelectedRecord, renderStats, emphasizeLastPhrase } from './template-components.mjs';

export function renderHomePage(context) {
  const {config,locale,packs,records,stats}=context; const t=createTranslator(locale,packs,config.defaultLocale);
  const latest=records[0]; const featured=records.filter(r=>r.featured).slice(0,Number(config.home?.featuredLimit||3)); const selected=featured.length?featured:records.slice(0,3);
  const months=[...groupBy(records,r=>r.monthKey).keys()].slice(0,Math.max(1,Number(config.home?.shelfMonths||5))); const shelfRecords=records.filter(r=>months.includes(r.monthKey));
  const heroStyle=`--hero-base:url('${escapeAttr(config.hero.baseImage)}');--hero-reveal:url('${escapeAttr(config.hero.revealImage)}')`;
  const sampleNotice=records.length&&records.every(r=>r.sample)?`<aside class="sample-notice section-shell"><strong>${escapeHtml(t('home.sampleNoticeTitle'))}</strong><p>${escapeHtml(t('home.sampleNoticeBody'))}</p></aside>`:'';
  const body=`
<section class="immersive-hero" data-immersive-hero style="${heroStyle}" aria-labelledby="hero-title">
  <div class="hero-image hero-image--base hero-zoom" aria-hidden="true"></div><div class="hero-image hero-image--reveal" aria-hidden="true"></div><div class="hero-scrim" aria-hidden="true"></div><div class="hero-grid" aria-hidden="true"></div>
  <div class="hero-heading"><p class="hero-overline hero-anim hero-fade" style="animation-delay:.12s"><span>${escapeHtml(t('hero.overline'))}</span><span>EST. ${escapeHtml(config.startYear)}</span></p><h1 id="hero-title"><span class="hero-title-accent hero-anim hero-reveal" style="animation-delay:.25s">${escapeHtml(t('hero.titleAccent'))}</span><span class="hero-title-main hero-anim hero-reveal" style="animation-delay:.42s">${escapeHtml(t('hero.titleMain'))}</span></h1><p class="hero-subline hero-anim hero-fade" style="animation-delay:.58s">${escapeHtml(t('hero.subline'))}</p></div>
  <aside class="hero-panel hero-panel--left hero-anim hero-fade" style="animation-delay:.7s"><span class="hero-panel-kicker">${escapeHtml(t('hero.leftLabel'))}</span><p>${escapeHtml(t('hero.leftBody'))}</p><dl class="hero-micro-stats"><div><dt>${escapeHtml(t('hero.volumeLabel'))}</dt><dd>${String(stats.records).padStart(2,'0')}</dd></div><div><dt>${escapeHtml(t('hero.dayLabel'))}</dt><dd>${String(stats.days).padStart(2,'0')}</dd></div><div><dt>${escapeHtml(t('hero.projectLabel'))}</dt><dd>${String(stats.projects).padStart(2,'0')}</dd></div></dl></aside>
  <aside class="hero-panel hero-panel--right hero-anim hero-fade" style="animation-delay:.85s"><p><span class="hero-copy-pointer">${escapeHtml(t('hero.rightBody'))}</span><span class="hero-copy-touch">${escapeHtml(t('hero.rightBodyTouch'))}</span></p><div class="hero-actions-premium"><a class="hero-primary-action" href="#catalogue">${escapeHtml(t('hero.primaryAction'))}${ICONS.arrow}</a><a class="hero-secondary-action" href="${escapeAttr(localizePath('/about/',locale,config.defaultLocale))}">${escapeHtml(t('hero.secondaryAction'))}</a></div>${latest?`<a class="hero-latest" href="${escapeAttr(localizePath(latest.url,locale,config.defaultLocale))}"><span>${escapeHtml(t('hero.latest'))}</span><div><time datetime="${escapeAttr(latest.date)}">${escapeHtml(formatDate(latest.date,locale))}</time><strong lang="${escapeAttr(latest.lang)}" dir="${escapeAttr(latest.dir)}">${escapeHtml(latest.title)}</strong></div>${ICONS.arrow}</a>`:''}</aside>
  <div class="spotlight-finder" data-spotlight-finder aria-hidden="true"><span></span><small>${escapeHtml(t('hero.moveToReveal'))}</small></div><a class="hero-scroll-cue hero-anim hero-fade" style="animation-delay:1.05s" href="#archive-story"><span>${escapeHtml(t('hero.scroll'))}</span><i aria-hidden="true"></i></a>
</section>
<section class="strata-intro section-shell" id="archive-story">${renderSectionLabel(t('home.introIndex'),t('home.introLabel'))}<div class="strata-intro-grid"><h2>${emphasizeLastPhrase(t('home.introTitle'),locale)}</h2><div class="strata-intro-copy"><p>${escapeHtml(t('home.introBody1'))}</p><p>${escapeHtml(t('home.introBody2'))}</p><a class="strata-text-link" href="${escapeAttr(localizePath('/about/',locale,config.defaultLocale))}">${escapeHtml(t('home.introLink'))}${ICONS.arrow}</a></div></div></section>
<section class="strata-stats section-shell" aria-label="${escapeAttr(t('home.statsLabel'))}">${renderStats(stats,t)}</section>${sampleNotice}
${records.length?`<section class="catalogue-stage" id="catalogue"><div class="section-shell catalogue-stage-heading">${renderSectionLabel(t('home.shelvesIndex'),t('home.shelvesLabel'))}</div><div class="section-shell catalogue-copy"><h2>${escapeHtml(t('home.shelvesTitle'))}</h2><p>${escapeHtml(t('home.shelvesDescription'))}</p></div>${renderArchiveExplorer({records:shelfRecords,locale,t,config,compact:true})}<div class="section-shell archive-more"><a href="${escapeAttr(localizePath('/archive/',locale,config.defaultLocale))}">${escapeHtml(t('common.viewAll'))}${ICONS.arrow}</a></div></section>`:renderFirstRecord({locale,t,config})}
${selected.length?`<section class="selected-section section-shell">${renderSectionLabel(t('home.selectedIndex'),t('home.selectedLabel'))}<div class="selected-heading"><h2>${escapeHtml(t('home.selectedTitle'))}</h2><p>${escapeHtml(t('home.selectedDescription'))}</p></div><div class="selected-grid">${selected.map((r,i)=>renderSelectedRecord(r,i,locale,t,config)).join('')}</div></section>`:''}
<section class="agent-section section-shell"><div class="agent-mark" aria-hidden="true">AI</div><div><p class="eyebrow">${escapeHtml(t('home.agentLabel'))}</p><h2>${escapeHtml(t('home.agentTitle'))}</h2><p>${escapeHtml(t('home.agentBody'))}</p></div><div class="agent-example"><span>${escapeHtml(t('home.agentExampleLabel'))}</span><p>${escapeHtml(t('home.agentExample'))}</p></div></section>`;
  return renderLayout({...context,pathname:'/',body,hero:true,description:t('meta.siteDescription')});
}
