const doc=document,root=doc.documentElement,body=doc.body;
const qs=(selector,parent=doc)=>parent?.querySelector(selector)??null;
const qsa=(selector,parent=doc)=>parent?[...parent.querySelectorAll(selector)]:[];
const normalize=(value='')=>String(value).normalize('NFKC').toLocaleLowerCase().replace(/[\p{Punctuation}\p{Symbol}]+/gu,' ').replace(/\s+/g,' ').trim();
const escapeHtml=(value='')=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
const formatTemplate=(template,variables={})=>String(template||'').replace(/\{([A-Za-z0-9_]+)\}/g,(_,key)=>variables[key]??`{${key}}`);
const storage={get(key){try{return localStorage.getItem(key);}catch{return null;}},set(key,value){try{localStorage.setItem(key,value);}catch{}}};

setupTheme();setupHeader();setupLocaleMenu();setupMobileNavigation();setupSpotlight();setupArchiveExplorers();setupGlobalSearch();setupReadingProgress();

function setupTheme(){const labels=safeJson(body.dataset.themeLabels,{auto:'Auto',light:'Light',dark:'Dark'}),order=['auto','light','dark'],stored=storage.get('shiori-theme'),initial=order.includes(stored)?stored:'auto';const apply=theme=>{root.dataset.theme=theme;qsa('[data-theme-icon]').forEach(icon=>{icon.hidden=icon.dataset.themeIcon!==theme;});qsa('[data-theme-toggle]').forEach(button=>{const next=order[(order.indexOf(theme)+1)%order.length];button.setAttribute('aria-label',labels[next]||labels.auto);button.title=labels[next]||labels.auto;});};apply(initial);qsa('[data-theme-toggle]').forEach(button=>button.addEventListener('click',()=>{const current=root.dataset.theme||'auto',next=order[(order.indexOf(current)+1)%order.length];storage.set('shiori-theme',next);apply(next);}));}

function setupHeader(){const header=qs('[data-site-header]'),hero=qs('[data-immersive-hero]');if(!header)return;let ticking=false;const update=()=>{ticking=false;header.classList.toggle('is-scrolled',hero?hero.getBoundingClientRect().bottom<=92:scrollY>12);};const request=()=>{if(ticking)return;ticking=true;requestAnimationFrame(update);};update();addEventListener('scroll',request,{passive:true});addEventListener('resize',request,{passive:true});}

function setupLocaleMenu(){qsa('[data-locale-switcher]').forEach(switcher=>{const button=qs('[data-locale-toggle]',switcher),menu=qs('[data-locale-menu]',switcher);if(!button||!menu)return;const close=(restore=false)=>{menu.hidden=true;button.setAttribute('aria-expanded','false');if(restore)button.focus();};const open=()=>{menu.hidden=false;button.setAttribute('aria-expanded','true');qs('a',menu)?.focus();};button.addEventListener('click',event=>{event.stopPropagation();menu.hidden?open():close();});menu.addEventListener('keydown',event=>{const links=qsa('a',menu),index=links.indexOf(doc.activeElement);if(event.key==='Escape'){event.preventDefault();close(true);}else if(event.key==='ArrowDown'){event.preventDefault();links[(index+1+links.length)%links.length]?.focus();}else if(event.key==='ArrowUp'){event.preventDefault();links[(index-1+links.length)%links.length]?.focus();}else if(event.key==='Tab'&&!event.shiftKey&&doc.activeElement===links.at(-1)){close();}});doc.addEventListener('click',event=>{if(!switcher.contains(event.target))close();});});}

function setupMobileNavigation(){const header=qs('[data-site-header]'),toggle=qs('[data-nav-toggle]',header),panel=qs('[data-mobile-nav]',header);if(!header||!toggle||!panel)return;const main=qs('main'),footer=qs('footer');let previousFocus=null;const setInert=value=>[main,footer].forEach(element=>{if(!element)return;value?element.setAttribute('inert',''):element.removeAttribute('inert');});const close=(restore=true)=>{panel.hidden=true;header.classList.remove('menu-is-open');root.classList.remove('menu-lock');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label',toggle.dataset.openLabel||'Open menu');setInert(false);if(restore&&previousFocus instanceof HTMLElement)previousFocus.focus();};const open=()=>{previousFocus=doc.activeElement;panel.hidden=false;header.classList.add('menu-is-open');root.classList.add('menu-lock');toggle.setAttribute('aria-expanded','true');toggle.setAttribute('aria-label',toggle.dataset.closeLabel||'Close menu');setInert(true);qs('a,button',panel)?.focus();};toggle.addEventListener('click',()=>panel.hidden?open():close());qsa('a',panel).forEach(link=>link.addEventListener('click',()=>close(false)));panel.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();close();return;}if(event.key!=='Tab')return;const focusable=qsa('a,button:not([disabled]),[tabindex]:not([tabindex="-1"])',panel).filter(el=>!el.hidden);if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&doc.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&doc.activeElement===last){event.preventDefault();first.focus();}});addEventListener('resize',()=>{if(innerWidth>760&&!panel.hidden)close(false);},{passive:true});}

function setupSpotlight(){const reduced=matchMedia('(prefers-reduced-motion: reduce)'),finePointer=matchMedia('(hover: hover) and (pointer: fine)');qsa('[data-immersive-hero]').forEach(hero=>{const finder=qs('[data-spotlight-finder]',hero);if(!finder)return;const radius=260,mouse={x:-999,y:-999},smooth={x:-999,y:-999};let raf=0,visible=true,engaged=false;const setPosition=(x,y)=>{hero.style.setProperty('--spot-x',`${x}px`);hero.style.setProperty('--spot-y',`${y}px`);hero.style.setProperty('--spot-radius',`${radius}px`);finder.style.transform=`translate3d(${x}px,${y}px,0)`;};const setStatic=()=>{const rect=hero.getBoundingClientRect(),x=rect.width*(innerWidth<760?.65:.62),y=rect.height*(innerWidth<760?.47:.56);mouse.x=smooth.x=x;mouse.y=smooth.y=y;setPosition(x,y);hero.dataset.spotlight='static';};const animate=()=>{if(visible&&finePointer.matches&&!reduced.matches){smooth.x+=(mouse.x-smooth.x)*.1;smooth.y+=(mouse.y-smooth.y)*.1;setPosition(smooth.x,smooth.y);}raf=requestAnimationFrame(animate);};const move=event=>{if(!finePointer.matches||reduced.matches)return;const rect=hero.getBoundingClientRect();mouse.x=Math.max(0,Math.min(rect.width,event.clientX-rect.left));mouse.y=Math.max(0,Math.min(rect.height,event.clientY-rect.top));if(!engaged){smooth.x=mouse.x;smooth.y=mouse.y;engaged=true;}hero.dataset.spotlight='active';};const observer=new IntersectionObserver(([entry])=>{visible=Boolean(entry?.isIntersecting);},{threshold:.01});observer.observe(hero);hero.addEventListener('pointermove',move,{passive:true});hero.addEventListener('pointerenter',()=>{if(finePointer.matches&&!reduced.matches)hero.dataset.spotlight='active';});hero.addEventListener('pointerleave',()=>{if(finePointer.matches&&!reduced.matches)hero.dataset.spotlight=engaged?'idle':'hidden';});addEventListener('resize',setStatic,{passive:true});reduced.addEventListener?.('change',setStatic);finePointer.addEventListener?.('change',setStatic);setStatic();raf=requestAnimationFrame(animate);addEventListener('pagehide',()=>{cancelAnimationFrame(raf);observer.disconnect();},{once:true});});}

function setupArchiveExplorers(){qsa('[data-archive-root]').forEach(archive=>{const form=qs('[data-archive-form]',archive),query=qs('[data-archive-query]',archive),count=qs('[data-filter-count]',archive),empty=qs('[data-filter-empty]',archive),shelfView=qs('[data-archive-view="shelf"]',archive),listView=qs('[data-archive-view="list"]',archive),shelfItems=qsa('[data-record-item]',shelfView),listItems=qsa('[data-record-item]',listView);if(!form||!query||!count||!empty)return;const resultOne=archive.dataset.resultOne||'1 record shown',resultMany=archive.dataset.resultMany||'{count} records shown',filters=['year','type','project','tag','language'],sort=qs('[data-archive-sort]',archive);let viewMode=storage.get('shiori-view')==='list'?'list':'shelf';
const readState=()=>({q:normalize(query.value),year:form.elements.year?.value||'',type:form.elements.type?.value||'',project:form.elements.project?.value||'',tag:form.elements.tag?.value||'',language:form.elements.language?.value||'',sort:sort?.value||'newest'});
const matches=(item,state)=>{if(state.q&&!normalize(item.dataset.search).includes(state.q))return false;if(state.year&&item.dataset.year!==state.year)return false;if(state.type&&item.dataset.type!==state.type)return false;if(state.project&&item.dataset.project!==state.project)return false;if(state.language&&item.dataset.language!==state.language)return false;if(state.tag&&!safeJson(item.dataset.tags,[]).includes(state.tag))return false;return true;};
const compare=(a,b,state)=>state.sort==='oldest'?String(a.dataset.date).localeCompare(String(b.dataset.date)):state.sort==='title'?String(a.dataset.title).localeCompare(String(b.dataset.title),body.dataset.locale||undefined,{sensitivity:'base',numeric:true}):String(b.dataset.date).localeCompare(String(a.dataset.date));
const updateUrl=state=>{if(archive.dataset.syncUrl!=='true'||!/^https?:$/.test(location.protocol))return;const params=new URLSearchParams();for(const[key,value]of Object.entries(state))if(value&&!(key==='sort'&&value==='newest'))params.set(key,value);const next=`${location.pathname}${params.size?`?${params}`:''}`;try{history.replaceState(null,'',next);}catch{}};
const sortShelves=state=>{if(!shelfView)return;const shelves=qsa('[data-shelf]',shelfView).sort((a,b)=>state.sort==='oldest'?String(a.dataset.month).localeCompare(String(b.dataset.month)):String(b.dataset.month).localeCompare(String(a.dataset.month)));shelves.forEach(shelf=>{const row=qs('.book-row',shelf),fill=qs('.shelf-fill',row),items=qsa('[data-record-item]',row).sort((a,b)=>compare(a,b,state));items.forEach(item=>row.insertBefore(item,fill));shelfView.append(shelf);});};
const apply=()=>{const state=readState();let visibleCount=0;shelfItems.forEach(item=>{const show=matches(item,state);item.hidden=!show;if(show)visibleCount+=1;});listItems.forEach(item=>{item.hidden=!matches(item,state);});qsa('[data-shelf]',archive).forEach(shelf=>{const visible=qsa('[data-record-item]',shelf).filter(item=>!item.hidden).length;shelf.hidden=visible===0;const value=qs('[data-shelf-count]',shelf);if(value)value.textContent=String(visible);});sortShelves(state);if(listView)listItems.filter(item=>!item.hidden).sort((a,b)=>compare(a,b,state)).forEach(item=>listView.append(item));empty.hidden=visibleCount!==0;count.textContent=formatTemplate(visibleCount===1?resultOne:resultMany,{count:visibleCount});updateUrl(state);};
const setView=mode=>{viewMode=mode==='list'?'list':'shelf';if(shelfView)shelfView.hidden=viewMode!=='shelf';if(listView)listView.hidden=viewMode!=='list';qsa('[data-view-mode]',archive).forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.viewMode===viewMode)));storage.set('shiori-view',viewMode);};
const params=new URLSearchParams(location.search);query.value=params.get('q')||'';filters.forEach(key=>{if(form.elements[key])form.elements[key].value=params.get(key)||'';});if(sort)sort.value=params.get('sort')||'newest';form.addEventListener('input',apply);form.addEventListener('change',apply);form.addEventListener('reset',()=>requestAnimationFrame(()=>{if(sort)sort.value='newest';apply();}));qsa('[data-filter-clear]',archive).forEach(button=>button.addEventListener('click',()=>{form.reset();requestAnimationFrame(apply);}));qsa('[data-view-mode]',archive).forEach(button=>button.addEventListener('click',()=>setView(button.dataset.viewMode)));doc.addEventListener('keydown',event=>{if(event.key==='/'&&!isTypingTarget(event.target)&&!qs('[data-search-dialog]')?.open){event.preventDefault();event.stopImmediatePropagation();query.focus();}});setView(viewMode);apply();});}

function setupGlobalSearch(){const dialog=qs('[data-search-dialog]'),input=qs('[data-global-search]',dialog),results=qs('[data-search-results]',dialog);if(!dialog||!input||!results||typeof dialog.showModal!=='function')return;let records=[],loaded=false,active=-1,returnFocus=null;const load=async()=>{if(loaded)return;const response=await fetch(body.dataset.searchIndex,{headers:{accept:'application/json'}});if(!response.ok)throw new Error(String(response.status));records=await response.json();loaded=true;};const open=async()=>{returnFocus=doc.activeElement;if(!dialog.open)dialog.showModal();input.focus();try{await load();render();}catch{results.innerHTML=`<div class="search-message"><p>${escapeHtml(dialog.dataset.loadingError)}</p></div>`;}};const close=()=>{if(dialog.open)dialog.close();active=-1;if(returnFocus instanceof HTMLElement)returnFocus.focus({preventScroll:true});};
const render=()=>{const raw=input.value.trim(),query=normalize(raw);active=-1;if(!query){results.innerHTML=`<div class="search-welcome"><p>${escapeHtml(dialog.dataset.empty)}</p></div>`;return;}const terms=query.split(' ').filter(Boolean);const matches=records.map(record=>{const title=normalize(record.title),tags=normalize(record.tags?.join(' ')),haystack=normalize([record.title,record.summary,record.text,record.project,record.language,record.languageLabel,record.typeLabel,...(record.tags||[])].join(' '));if(!terms.every(term=>haystack.includes(term)))return null;const score=terms.reduce((total,term)=>total+(title.includes(term)?6:0)+(tags.includes(term)?3:0)+1,0);return{record,score};}).filter(Boolean).sort((a,b)=>b.score-a.score||String(b.record.date).localeCompare(String(a.record.date))).slice(0,30);if(!matches.length){results.innerHTML=`<div class="search-message"><p>${escapeHtml(formatTemplate(dialog.dataset.noResults,{query:raw}))}</p><small>${escapeHtml(dialog.dataset.noResultsHint)}</small></div>`;return;}results.innerHTML=matches.map(({record},index)=>`<a class="search-result" href="${escapeHtml(record.url)}" data-search-result data-index="${index}"><span class="search-result-date">${escapeHtml(record.shortDate)}</span><span><small>${escapeHtml(record.typeLabel)} · ${escapeHtml(record.languageLabel)}${record.project?` · ${escapeHtml(record.project)}`:''}</small><strong lang="${escapeHtml(record.language)}">${highlight(record.title,raw)}</strong><p lang="${escapeHtml(record.language)}">${highlight(record.summary,raw)}</p></span><svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6"/></svg></a>`).join('');};
const setActive=next=>{const items=qsa('[data-search-result]',results);if(!items.length)return;active=(next+items.length)%items.length;items.forEach((item,index)=>item.classList.toggle('is-active',index===active));items[active].scrollIntoView({block:'nearest'});};qsa('[data-search-open]').forEach(button=>button.addEventListener('click',open));qs('[data-search-close]',dialog)?.addEventListener('click',close);dialog.addEventListener('cancel',event=>{event.preventDefault();close();});dialog.addEventListener('click',event=>{if(event.target===dialog)close();});input.addEventListener('input',render);input.addEventListener('keydown',event=>{if(event.key==='ArrowDown'){event.preventDefault();setActive(active+1);}else if(event.key==='ArrowUp'){event.preventDefault();setActive(active-1);}else if(event.key==='Enter'&&active>=0){event.preventDefault();qsa('[data-search-result]',results)[active]?.click();}});doc.addEventListener('keydown',event=>{if(event.key==='/'&&!isTypingTarget(event.target)&&!dialog.open){event.preventDefault();open();}if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();dialog.open?close():open();}if(event.key==='Escape'&&dialog.open)close();});}

function highlight(text,rawQuery){const source=String(text),terms=String(rawQuery).normalize('NFKC').toLocaleLowerCase().split(/\s+/).filter(Boolean).slice(0,5);if(!terms.length)return escapeHtml(source);const chars=[...source],map=[],folded=[];let offset=0;for(const char of chars){const start=offset,end=offset+char.length,norm=char.normalize('NFKC').toLocaleLowerCase();for(const unit of norm){folded.push(unit);map.push([start,end]);}offset=end;}const haystack=folded.join(''),ranges=[];for(const term of terms){let from=0;while(from<haystack.length){const index=haystack.indexOf(term,from);if(index<0)break;const start=map[index]?.[0]??0,end=map[index+term.length-1]?.[1]??start;ranges.push([start,end]);from=index+Math.max(1,term.length);}}ranges.sort((a,b)=>a[0]-b[0]);const merged=[];for(const range of ranges){const previous=merged.at(-1);if(previous&&range[0]<=previous[1])previous[1]=Math.max(previous[1],range[1]);else merged.push([...range]);}let output='',cursor=0;for(const[start,end]of merged){output+=escapeHtml(source.slice(cursor,start));output+=`<mark>${escapeHtml(source.slice(start,end))}</mark>`;cursor=end;}return output+escapeHtml(source.slice(cursor));}

function setupReadingProgress(){const progress=qs('[data-reading-progress]'),article=qs('[data-record-page]');if(!progress||!article){if(progress)progress.hidden=true;return;}const update=()=>{const rect=article.getBoundingClientRect(),total=Math.max(1,article.offsetHeight-innerHeight),passed=Math.min(total,Math.max(0,-rect.top));progress.value=Math.round(passed/total*100);};update();addEventListener('scroll',update,{passive:true});addEventListener('resize',update,{passive:true});}
function isTypingTarget(target){return target instanceof HTMLElement&&(target.matches('input,textarea,select')||target.isContentEditable);}
function safeJson(value,fallback){try{return JSON.parse(value);}catch{return fallback;}}
